# r_cmd_check workflow

name: r_cmd_check

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  r_cmd_check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Use R version 3.6.3
        uses: r-lib/actions/setup-r@v2
        with:
          r-version: '3.6.3'

      - name: Install dependencies
        run: |
          install.packages(c("remotes", "rcmdcheck"))
          remotes::install_deps(dependencies = TRUE)
          shell: Rscript {0}

      - name: R CMD Build
        run: |
          R CMD build --no-build-vignettes --no-manual . 
          R CMD INSTALL *.tar.gz 
        shell: bash
          
      - name: Check
        run: rcmdcheck::rcmdcheck(path = ".", args = "--no-manual", error_on = "error")
        shell: Rscript {0}

      - name: Upload check results
        uses: actions/upload-artifact@main
        with:
          name: rcmdcheck-results
